# Plot ACF dan PACF Return Saham
# Read the data from the Excel file
library(TSA)
library(readxl)
data <- read_excel("Return.xlsx")

# Extract the variables
RTBBCA <- as.numeric(data$BBCA_RT)
RTBBRI <- as.numeric(data$BBRI_RT)
RTBMRI <- as.numeric(data$BMRI_RT)
RTBBNI <- as.numeric(data$BBNI_RT)
RTIHSG <- as.numeric(data$IHSG_RT)

par(mfrow=c(2,1))
acf(RTBBCA,main="Return BBCA")
pacf(RTBBCA,main="Return BBCA")
eacf(RTBBCA)
# Calon model (0,3),(1,3),(0,4)
par(mfrow=c(2,1))
acf(RTBBRI,main="Return BBRI")
pacf(RTBBRI,main="Return BBRI")
eacf(RTBBRI)
# Calon model (0,2),(1,1),(2,1)
par(mfrow=c(2,1))
acf(RTBBNI,main="Return BBNI")
pacf(RTBBNI,main="Return BBNI")
eacf(RTBBNI)
# Calon model (0,1),(1,1),(2,2)
par(mfrow=c(2,1))
acf(RTBMRI,main="Return BMRI")
pacf(RTBMRI,main="Return BMRI")
eacf(RTBMRI)
# Calon model (0,0),(1,1),(2,2)
par(mfrow=c(2,1))
acf(RTIHSG,main="Return IHSG")
pacf(RTIHSG,main="Return IHSG")
eacf(RTIHSG)
# Calon model (0,3),(1,3),(2,3)
